### PR TITLE
Fix for minor bug in nowplaying.py (Unicode playing information caused exception)

### PR DESCRIPTION
**Pull request by woodruffw**

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks for the patch, I have added it to my own local copy, as it fixes the display of Japanese song titles. I hope this could be merged.

**Comment by woodruffw** [comment]
Yep, that's exactly what I used it for in my local copy.
Glad to hear it works well for someone else.

**Comment by FichteFoll** [comment]
Can anyone fill me in on the actual error message that was produced? I believe this can also be fixed using `from __future__ import unicode_literals` because the error is most likely produced when the `cmd` string is constructued using `.format()`. I can't verify however.

**Comment by woodruffw** [comment]
I don't remember the actual error message, but you should be able to repro it by removing the changes and attempting to report a song that's playing with UTF-8 track information. If `unicode_literals` fixes that, it's probably preferable to an explicit `encode` call.

**Pull request merged**
